name: Go CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
 build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: go build -v ./cmd/api
    - name: Test
      run: go test -v ./...

 docker:
    name: Build and Run Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build and run Docker container
      run: |
        docker build -t biblioteca-app .
        docker run -d --name biblioteca-app-container biblioteca-app

 integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run integration tests
      run: |
        docker-compose up -d
        go test -v ./...
        docker-compose down

 publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: user/biblioteca-app:latest
